<?php
/** @var \Riverstone\AiContentGenerator\Block\Adminhtml\Product\Helper $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div data-bind="scope: 'riverstone-ai-product-helper'" class="riverstone-ai-product-helper">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<input type="hidden" id="openai_url" name="openai_url" value="<?php echo $block->getUrl('riverstone_aicontentgenerator/generate/index')?>">
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "riverstone-ai-product-helper": <?= /* @noEscape */ $block->getComponentJsonConfig() ?>
                }
            }
        }
    }
</script>

<div id="custom-page-modal" style="display:none;">
    <form id="fetch_ai_content-form">
        <div class="admin__field">
            <div class="popup-form-label"><label><span id="dynamic-span"></span></label></div>
            <div class="admin__field-control">
                <input class="admin__control-text" id="current_attribute_value" type="text" name="current_value">
            </div>
        </div>
        <div class="admin__field">
            <div class="popup-form-label"><label><span><?= $block->escapeHtml(__('Prompt')) ?></span></label></div>
            <div class="admin__field-control">
                <textarea id="default_prompt_value" name="default_prompt" rows="3" class="textarea admin__control-textarea"></textarea>
                </div>
        </div>
        <div class="admin__field" id="generated_content_div">
            <div class="popup-form-label"><label><span><?= $block->escapeHtml(__('Generated Content')) ?></span></label></div>
            <div class="admin__field-control">
                <input class="admin__control-text" type="text" id="generated_content"
                    name="prompt">
                </div>
        </div>
        <div class="admin__field ai-submit">
            <button class="action-default primary generate" type="button" id="fetch-ai-generate"><?= $block->escapeHtml(__('Generate Content')) ?></button>
            <button class="action- scalable action-secondary replace" type="button" id="fetch-ai-replace"><?= $block->escapeHtml(__('Replace Content')) ?></button>
        </div>
    </form>
</div>

<script>
    require(['jquery', 'mage/adminhtml/wysiwyg/tiny_mce/setup'], function ($) {
        $("body").delegate("#fetch-ai-generate", "click", function() {
 
            let data = new FormData();
            let prompt = $("#default_prompt_value").val();
            let attributeName = $("#current_attribute_key").val();
            if(prompt == ''){
                alert("Prompt Cannot be empty");
            } else {
                let payload ={
                    'form_key': FORM_KEY,
                    'prompt': prompt,
                };

            let result = true;

            console.log(data);

            $.ajax({
            type: 'POST',
            url: jQuery('#openai_url').val(),
            dataType: 'json',
            cache: false,
            showLoader: true,
            data: {'form_key': FORM_KEY, 'prompt': prompt},
            success : function(result){
                var status = result.type;
                if(status == "success"){
                    $('#generated_content_div').show();
                    $('#generated_content').val(result.result);
                    $('#fetch-ai-replace').show();
                }
                else{
                    alert("Something Went Wrong");
                }
            }
            });
            }
        });
        $("body").delegate("#fetch-ai-replace", "click", function() {
            var attributeName = $("#current_attribute_key").val();
            var selector = '[name="product[' + attributeName + ']"]';
            var inputElement = $(selector);
            if(inputElement){
                alert("yes")
            }else{
                alert("no")
            }
            var attributeName = $('#current_attribute_key').val();
            if(attributeName == 'short_description'){
                $("#product_form_short_description").val('<p>'+$('#generated_content').val()+'</p>');
                var editor = tinymce.get('product_form_short_description');
                if (editor) {
                    editor.setContent('<p>'+$('#generated_content').val()+'</p>');
                }
            }else{
                inputElement.val($('#generated_content').val()).trigger('change');
            }
            
            $('#custom-page-modal').modal('closeModal');
        })
    });
</script>